### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by PhanThanhTrung** [ruhyadi/YOLO3D#10]
First of all, I want to say that I really appreciate your work.
- I see in `inference.py` that at each time we predict an image, we have to init an instance of `DetectMultiBackend`. I think it will slow down your inference code when you want to infer many images. 
- You can speed up your inference code by predicting a batch of images instead of predicting a single image.

**Comment by ruhyadi** [comment]
That's right, I've updated the inference code in a different repository, please check [ruhyadi/yolo3d-lightning](https://github.com/ruhyadi/yolo3d-lightning). I also use the mechanism as you recommend, but I haven't checked how many improvements there are.

**Comment by PhanThanhTrung** [comment]
btw, this is not relevant to the inference speed but I notice that you visualize 3D box on the original image. This image is also used to crop ROI with 2D bounding box. There's a case when 2D bounding box is overlap, and you will crop to the region you visualized before. This is an example: 
![hi](https://user-images.githubusercontent.com/39378219/178653911-d9f52b72-fb4d-4463-abcf-8b7a9f734f33.jpg)

**Comment by ruhyadi** [comment]
Nice to notice that. This turns out, as you said, because croping and drawing bounding-box images are done by looping one by one. I think this problem is solved in the [new inference code](https://github.com/ruhyadi/YOLO3D/blob/main/inference.py).

**Comment by PhanThanhTrung** [comment]
@ruhyadi I'm gonna close this issue cause you already have another version of the inference code. I hope I could contribute to your repository in the future.
