### ISSUE TITLE
what does count mean in scripts/class_averages.txt?

### ISSUE THREAD

**Issue by mvpzhangqiu** [ruhyadi/YOLO3D#14]

**Comment by mvpzhangqiu** [comment]
![1674963424957(1)](https://user-images.githubusercontent.com/14309504/215303395-40b30114-88ae-4400-a5f3-faaf75ec2726.jpg)

**Comment by ruhyadi** [comment]
The "count" means how many "car" or "any" objects are read in the "labels" dataset. This "count" will be used to "average" all the variables (dimensions).
As far as I know, the dimension variable is in centimeters, but please refer to the paper: [https://arxiv.org/abs/1612.00496](https://arxiv.org/abs/1612.00496)
